import Head from "next/head";
import { AboutUS, Latest, Team } from "../sections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <AboutUS />
        <Latest/>
        <Team/>
      </div>
    </div>
  );
}
