import Head from "next/head";
import { Landing } from "../components/Landing/Landing";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Landing/>
    </div>
  );
}
