import Head from "next/head";
import { Contact, Footer, Header, Hero, Stats } from "../sections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Estato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <Stats />
      <Contact />
      <Footer />
    </div>
  );
}
